name: BuildAction

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/graemefoster/azurediagramsgithubactionsdocker:latest
            ghcr.io/graemefoster/azurediagramsgithubactionsdocker:0.6.30
